version: '3.8'

services:
  se-postgres:
    container_name: se-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: se202513
      POSTGRES_DB: se_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - se-network

  se-redis:
    container_name: se-redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - se-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  se-network: